#!/usr/bin/env bash

# Calc git root
GIT_ROOT=`git rev-parse --show-superproject-working-tree`
if [ -z "$GIT_ROOT" ]; then
	GIT_ROOT=`git rev-parse --show-toplevel`
fi

# hook-the-hooks
HOOK_NAME=`basename $0`
${GIT_ROOT}/asset/git/hooks/hook-the-hooks.sh ${HOOK_NAME}

# Check if status
if [ $? -ne 0 ]; then
    exit 1
fi

# Get target files (.php .phtml .html)
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(php|phtml|html)$')

# Deny patterns
PATTERNS='(var_dump|print_r|dd|die|exit|\$_GET|\$_POST|\$_REQUEST|\$_COOKIE|\$_SESSION|\$_SERVER)'

FOUND=0

# Loop files
for FILE in $FILES; do
    # grep with line number
    MATCHES=$(git show ":$FILE" | grep -nE "$PATTERNS")

    if [ -n "$MATCHES" ]; then
        FOUND=1
        echo ""
        echo "🚫 Forbidden patterns found in: $FILE"
        echo "---------------------------------------"
        echo "$MATCHES"
        echo ""
    fi
done

if [ $FOUND -eq 1 ]; then
    echo "❌ Commit aborted due to forbidden patterns."
    echo ""
    echo "Use replacements:"
    echo "  var_dump(), print_r(), dd(), die(), exit() → D()"
    echo "  \$_GET, \$_POST, \$_REQUEST, \$_COOKIE, \$_SESSION, \$_SERVER → OP()->Request()"
    exit 1
fi

exit 0
